version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/scrap"
    target-branch: "dev"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
