version: '2.0'
services:
  scrapper:
    image: node:20-alpine
    working_dir: /app
    restart: on-failure:3
    volumes:
     - ./scrap:/app
     - ./resources:/var/resources
     - ./monthly-resources:/var/monthly-resources
     - ./config:/etc/scrapconfig
    entrypoint: sh local.sh
    user: $UID:$GID

  web:
    image: python:3.12-alpine
    working_dir: /var/www
    restart: on-failure:3
    volumes:
     - ./web:/var/www
     - ./resources:/var/www/resources
     - ./monthly-resources:/var/www/monthly-resources
    entrypoint: python3 -m http.server -d . 8080
    ports:
      - "80:8080"

