services:
  scrapper:
    image: node:18-alpine
    working_dir: /app
    restart: on-failure:3
    volumes:
     - ./scrap:/app
     - ./resources:/var/resources
     - ./config:/etc/scrapconfig
    entrypoint: sh local.sh
    user: $UID:$GID
