([... document.querySelectorAll('.local-icon')])
	.forEach( (srcElem) => fetch(`./assets/${srcElem.innerText}.svg`)
							.then( res => res.text() )
							.then( txt => srcElem.parentNode.innerHTML = txt )
	)